version: '2'
services:
  opa:
    hostname: opa
    container_name: opa
    image: openpolicyagent/opa:latest
    ports:
      - "8181:8181"
    command: "run --server --log-level=debug --watch /policies"
    volumes:
      - ./policies:/policies

  zookeeper:
    image: confluentinc/cp-zookeeper:5.5.2
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SASL_ENABLED: "false"
      ZOOKEEPER_TICK_TIME: 2000
      KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/zookeeper_server_jaas.conf
          -Dzookeeper.authProvider.1=org.apache.zookeeper.server.auth.SASLAuthenticationProvider" 
    volumes:
      - ./configs/zookeeper_server_jaas.conf:/etc/kafka/zookeeper_server_jaas.conf

  kafka:
    image: ghcr.io/raft-tech/kafka-summit-2021/kafka-opa
    hostname: kafka
    container_name: kafka
    depends_on:
      - zookeeper
      - opa
    ports:
      - "9092:9092"
    environment:
      KAFKA_AUTHORIZER_CLASS_NAME: tech.goraft.kafka.opa.OpaAuthorizer
      KAFKA_OPA_AUTHORIZER_URL: "http://opa:8181/v1/data/kafka/authz/allow"
      KAFKA_OPA_AUTHORIZER_ALLOW_ON_ERROR: "false"
      KAFKA_OPA_AUTHORIZER_CACHE_INITIAL_CAPACITY: 100
      KAFKA_OPA_AUTHORIZER_CACHE_MAXIMUM_SIZE: 100
      KAFKA_OPA_AUTHORIZER_CACHE_EXPIRE_AFTER_MS: 600000
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:SASL_PLAINTEXT
      KAFKA_LISTENERS: INTERNAL://:29092,EXTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://:29092,EXTERNAL://:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      ZOOKEEPER_SASL_ENABLED: "false"
      KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/kafka_server_jaas.conf"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    volumes:
      - ./configs/kafka_server_jaas.conf:/etc/kafka/kafka_server_jaas.conf

  control-center:
    image: confluentinc/cp-enterprise-control-center:5.5.2
    hostname: control-center
    container_name: control-center
    depends_on:
      - kafka
    ports:
      - "9021:9021"
    environment:
      CONTROL_CENTER_ID: 1
      CONTROL_CENTER_BOOTSTRAP_SERVERS: "kafka:29092"
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
      CONFLUENT_METRICS_TOPIC_REPLICATION: 1
      PORT: 9021
      CONFLUENT_CONTROL_CENTER_STREAMS_SASL_MECHANISM: PLAIN
      CONFLUENT_CONTROL_CENTER_STREAMS_SECURITY_PROTOCOL: SASL_PLAINTEXT
      CONTROL_CENTER_OPTS: "-Djava.security.auth.login.config=/etc/kafka/controlcenter_client_jaas.conf"
    volumes:
      - ./configs/controlcenter_client_jaas.conf:/etc/kafka/controlcenter_client_jaas.conf

  pii-datagen:
    image: ghcr.io/raft-tech/kafka-summit-2021/pii-datagen
    # build: ./pii-datagen
    hostname: pii-datagen
    container_name: pii-datagen
    environment:
      BOOTSTRAP_SERVERS: "kafka:9092"
      KAFKA_TOPIC: pii
      SASL_USERNAME: admin
      SASL_PASSWORD: admin-secret

  kafka-streams-bobjones:
    image: ghcr.io/raft-tech/kafka-summit-2021/kafka-streams-message-security
    # build: ./kafka-streams-message-security
    hostname: kafka-streams-bobjones
    container_name: kafka-streams-bobjones
    environment:
      APPLICATION_ID: kafka-streams-bobjones
      BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_TOPIC: pii
      KAFKA_SASL_ENABLED: "true"
      SASL_USERNAME: bobjones
      SASL_PASSWORD: bobjones-secret
  
  kafka-streams-alicesmith:
    image: ghcr.io/raft-tech/kafka-summit-2021/kafka-streams-message-security
    # build: ./kafka-streams-message-security
    hostname: kafka-streams-alicesmith
    container_name: kafka-streams-alicesmith
    environment:
      APPLICATION_ID: kafka-streams-alicesmith
      BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_TOPIC: pii
      KAFKA_SASL_ENABLED: "true"
      SASL_USERNAME: alicesmith
      SASL_PASSWORD: alicesmith-secret

  kafka-streams-johnhernandez:
    image: ghcr.io/raft-tech/kafka-summit-2021/kafka-streams-message-security
    # build: ./kafka-streams-message-security
    hostname: kafka-streams-johnhernandez
    container_name: kafka-streams-johnhernandez
    environment:
      APPLICATION_ID: kafka-streams-johnhernandez
      BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_TOPIC: pii
      KAFKA_SASL_ENABLED: "true"
      SASL_USERNAME: johnhernandez
      SASL_PASSWORD: johnhernandez-secret
    